version: '3.8'

services:
  mariadb: 

    #DEBUG commands:
    # docker exec -it mariadb bash
    # > mysql -u stanislavlia42 -p


    image:  mariadb:prod
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: ./Dockerfile

    env_file:
      - .env
    networks:
      - inception
    
    # volumes: #No volumes for now
    #   - ""
    
networks:
  inception:
    name: inception
