version: '3.8'

services:
  mariadb:
    image:  mariadb:prod
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: ./Dockerfile

    env_file:
      - .env
    networks:
      - inception
    
    # volumes: #No volumes for now
    #   - ""
    
networks:
  inception:
    name: inception
