version: '3.8'

services:

  # portainer: #Use Portainer for Debug
  #   image: portainer/portainer-ce:latest
  #   container_name: portainer
  #   restart: always
  #   ports:
  #     - "9000:9000"  
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock 
  #     - portainer_data:/data  
  #   networks:
  #     - inception

  mariadb: 

    #DEBUG commands:
    # docker exec -it mariadb bash
    # > mysql -u stanislavlia42 -p
    image:  mariadb:prod
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: ./Dockerfile

    env_file:
      - .env
    networks:
      - inception

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3




  wordpress:
    image: wordpress:prod
    build:
      context: ./requirements/wordpress/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    
    
networks:
  inception:
    name: inception

volumes:
  portainer_data: