version: "3.8"

services:
  user-generator:
    container_name: user-generator
    image: user-generator:latest
    build: ./user-generator-service
    ports:
      - "7777:7777"  # Expose port 7777 for the FastAPI service
    networks:
      - playground

  nginx-reverse-proxy:
    container_name: nginx
    image: nginx:stable
    ports:
      - "9999:9999"  # Expose port  for HTTP traffic
    networks:
      - playground
    volumes:
      - ./nginx-conf.conf:/etc/nginx/nginx.conf:ro  # Mount custom NGINX config



    #Can access our service in http://generate-user:9999/user

networks:
  playground:
    name: playground
